---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: java
    tag: "8"

params: 
  MOVIE_FUN_URL:

inputs:
- name: movie-fun

run:
  path: movie-fun/ci/tasks/smoke-test.sh


